name= "Manuel Bernardelli"
print(len(name))
print(name.find("e"))
print(name.capitalize())
print(name.upper())
print(name.lower())
print(name.isalpha())
print(name.isdigit())
print(name.count("o"))
print(name.replace(" ", "a"))
print(name * 8)